### PR TITLE
feat: 'go to dashboard' btn when logged in

### PR DESCRIPTION
**Pull request by CityIsBetter**
In the home page, once the user is logged in, it doesn't make sense to have login button, which actually just redirects to academia page. so using the cookie, and finding if user is logged in, I have decided to show "go to dashboard" button, which will redirect to academia page.

image

feel free to change "go to dashboard" to any other phrase, but i hope you get the idea.

### CODE REVIEW

**Comment by CityIsBetter** [comment]
yelp, my bad for not unstaging the package-json, hence the +8690 lines

**Comment by Rahuletto** [comment]
Wait doesnt it redirect to the academia page by default?

**Comment by Rahuletto** [comment]
and can u remove package-lock and do another commit? we are using bun and not npm

**Comment by CityIsBetter** [comment]
> Wait doesnt it redirect to the academia page by default?

well yes, as i said before, it just didnt feel right to have it has "login" button even tho its already logged in.

**Review by Rahuletto — APPROVED** [review]
LGTM!

**Pull request merged**
